FROM centos:centos7.5.1804
MAINTAINER yerikyu "yerik_shu@139.com"
WORKDIR /usr/local/src
RUN yum install -y ntpdate epel-release python-devel git net-tools &&\
    yum install -y sudo &&\
    yum install -y iproute iproute-doc
